# Generated by Django 5.2.7 on 2025-10-08 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('meta_monetaria', models.DecimalField(decimal_places=2, default=0, help_text='Meta en dinero (0 si es de artículos)', max_digits=10)),
                ('recaudado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('ACT', 'Activa'), ('PAU', 'Pausada'), ('FIN', 'Finalizada')], default='ACT', max_length=3)),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria')),
            ],
            options={
                'verbose_name_plural': 'Campañas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MON', 'Monetaria'), ('ART', 'Artículo/Especie')], default='MON', max_length=3)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('articulo_descripcion', models.CharField(blank=True, help_text='Descripción del artículo si no es monetaria', max_length=255)),
                ('fecha_donacion', models.DateTimeField(auto_now_add=True)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campana')),
                ('donante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donaciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Donaciones',
                'ordering': ['-fecha_donacion'],
            },
        ),
    ]
