# Generated by Django 5.2.7 on 2025-10-08 05:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campana',
            options={},
        ),
        migrations.AlterModelOptions(
            name='donacion',
            options={},
        ),
        migrations.RemoveField(
            model_name='donacion',
            name='articulo_descripcion',
        ),
        migrations.AddField(
            model_name='donacion',
            name='articulo_donado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campana',
            name='estado',
            field=models.CharField(choices=[('ACT', 'Activa'), ('COM', 'Completada'), ('CAN', 'Cancelada')], default='ACT', max_length=3),
        ),
        migrations.AlterField(
            model_name='campana',
            name='fecha_limite',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='campana',
            name='meta_monetaria',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='campana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donaciones', to='core.campana'),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='donante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='tipo',
            field=models.CharField(choices=[('MON', 'Monetaria'), ('ART', 'Artículo')], max_length=3),
        ),
    ]
