# Generated by Django 5.2.7 on 2025-10-09 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_campana_options_alter_donacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen principal de la campaña.', null=True, upload_to='campana_pics/'),
        ),
    ]
